export const SHOW_ACTION_SHEET = 'SHOW_ACTION_SHEET';
export const HIDE_ACTION_SHEET = 'HIDE_ACTION_SHEET';
export const CLEAR_FEED_LIST = 'ClEAR_FEED_LIST';
export const REQUEST_FEED_LIST = 'REQUEST_FEED_LIST';
export const REQUEST_FEED_LIST_FAILURE = 'REQUEST_FEED_LIST_FAILURE';
export const FEED_LIST = 'FEED_LIST';
export const SWITCH_TOPIC = 'SWITCH_TOPIC';
